branches:
  only:
    - master
    - travis
    - setup

git:
  depth: 1
  submodules: false

sudo: required

language: cpp

matrix:
  include:
    - name: "linux"
      os: linux
      dist: xenial
      compiler: gcc

    - name: "osx"
      os: osx
      before_install:
        - brew install bison
        - export PATH="/usr/local/opt/bison/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/bison/lib"

addons:
  apt:
    update: true
    packages:
      - flex
      - bison
      - libboost-all-dev
      - z3
      - libz3-dev
  homebrew:
    update: true
    packages:
      - flex
      - python
      - boost
      - boost-python
      - z3

cache:
  directories:
    - $HOME/_cache

before_script:
  - cd $HOME
  - git clone https://github.com/Bo-Yuan-Huang/ILAng.git
  - cd ILAng
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - source "scripts/$BRANCH.sh"

notifications:
    email: false
