branches:
  only:
    - master

sudo: required

language: cpp

os: linux
dist: xenial

services:
  - docker

before_install:
  - docker pull byhuang/ilang:IMDb-ci

script:
  - docker build -t ci -f scripts/Dockerfile.ci .

notifications:
    email: false

