branches:
  only:
    - master

git:
  depth: 1
  submodules: false

sudo: required

language: cpp

cache:
  directories:
    - $HOME/_cache

matrix:
  include:
    - name: "linux-gcc"
      os: linux
      dist: xenial
      compiler: gcc

    - name: "linux-clang"
      os: linux
      dist: xenial
      compiler: clang
      before_install:
        - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

addons:
  apt:
    update: true
    packages:
      - bison
      - flex
      - libboost-all-dev
      - libz3-dev
      - z3

install:
  - cd $TRAVIS_BUILD_DIR
  - git clone --depth=1 https://github.com/Bo-Yuan-Huang/ILAng.git
  - mkdir -p ILAng/build && cd ILAng/build
  - cmake .. -DILANG_INSTALL_DEV=ON
  - make -j$(nproc)
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - git clone --depth=1 https://github.com/PrincetonUniversity/Itsy.git
  - cd Itsy
  - bjam -j$(nproc)
  - export PYTHONPATH=$(pwd)/build:$PYTHONPATH

script:
  - cd $TRAVIS_BUILD_DIR
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export CITEST_FILE="$BRANCH.sh"
  - export CITEST_DEFINED="$(find scripts/ci -name $CITEST_FILE | grep -c $CITEST_FILE)"
  - if [ $CITEST_DEFINED != "0" ] ; then source "scripts/ci/$CITEST_FILE" ; fi

notifications:
    email: false

